### ISSUE TITLE
can't use it

### ISSUE THREAD

**Issue by AnsonGames** [amazeedaizee/CustomStreamMaker#1] opened 2024-06-11 07:10 UTC
I tried almost every way to start the exe file including cmd and run as administrator but simply nothing happened

**Comment by amazeedaizee** [comment] 2024-06-14 13:45
Hi there! Sorry that the exe isn't working for you.

Is it ok if I know what operating system that you're using?

Can I also look at what happens in Event Viewer when the program tries to open?
Go to Windows Logs > Application, then on the right there's Find: type in CustomStreamMaker.exe and send me any screenshots of errors and/or warnings that appear.

**Comment by AnsonGames** [comment] 2024-06-15 13:47
Framework 版本: v4.0.30319
说明: 由于未经处理的异常，进程终止。
异常信息: System.NullReferenceException
   在 CustomStreamMaker.Program.OnAssemblyResolve(System.Object, System.ResolveEventArgs)
   在 System.AppDomain.OnAssemblyResolveEvent(System.Reflection.RuntimeAssembly, System.String)

异常信息: System.IO.FileLoadException
   在 CustomStreamMaker.StreamEditor..ctor()
   在 CustomStreamMaker.Program.Main()




Framework version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
unhandled exception:System.NullReferenceException
at CustomStreamMaker.Program.OnAssemblyResolve(System.Object, System.ResolveEventArgs)
at System.AppDomain.OnAssemblyResolveEvent(System.Reflection.RuntimeAssembly, System.String)

unhandled exception: System.IO.FileLoadException
at CustomStreamMaker.StreamEditor..ctor()
at CustomStreamMaker.Program.Main()

**Comment by AnsonGames** [comment] 2024-06-15 13:50
should I also update files like C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_CustomStreamMake_balabala

Also thanks for helping

**Comment by amazeedaizee** [comment] 2024-06-16 21:33
Hello, thanks for giving me this! It would really help with diagnosing the issue.

Right now, I don't have access to my personal PC at the moment, however I'll still try and look out what the source of the problem could be based on the info given.

**Comment by amazeedaizee** [comment] 2024-06-16 22:52
For now, since the problem seems to be related to resolving assemblies, can you add the exe itself into the assemblies folder and try and open it from there to see if there's still an issue?

**Comment by AnsonGames** [comment] 2024-06-18 10:00
oh it's win 11 and I didn't really know how to add it to assemblies folder. when i right click or ctrl v in the assemblies folder nothing happened.
![1718704840488](https://github.com/amazeedaizee/CustomStreamMaker/assets/131215887/9205d813-2cd1-4bf7-a0b8-6d64a39e6c48)

**Comment by amazeedaizee** [comment] 2024-06-20 08:42
I didn't really mean the GAC, if you downloaded the program through the Releases page, there should be two things in the zip file: the program executable and a folder called "Assemblies"; the libraries that the program uses. What I meant was to add the program executable to the "Assemblies" folder that was provided in the zip (after extracting everything)

**Comment by AnsonGames** [comment] 2024-06-28 14:25
![ed727f31d1eb28970460d60383a0ac5e](https://github.com/amazeedaizee/CustomStreamMaker/assets/131215887/51372bd2-273f-4602-960d-47968f970bca)
like this?it still didn't work

**Comment by amazeedaizee** [comment] 2024-07-01 07:46
Can you also try and copying the "Assembly-CSharp.dll" from the game files to the Assemblies folder as well? And see if the program opens? You can find this file by going to NEEDY GIRL OVERDOSE/Windose_Data/Managed

Again, sorry for the inconvenience!

**Comment by AnsonGames** [comment] 2024-07-04 17:00
now it gives me a window but it not actually working...

 ************** 异常文本 **************
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 CustomStreamMaker.GameLocation.InitializeValidGamePath() 位置 C:\Users\Angel\Desktop\hmm\bepin\CustomStreamMaker\GameLocation.cs:行号 18
   在 CustomStreamMaker.AssetExtractor.GetAddressablesPath() 位置 C:\Users\Angel\Desktop\hmm\bepin\CustomStreamMaker\AssetExtractor.cs:行号 63
   在 CustomStreamMaker.AssetExtractor.CacheBackgrounds() 位置 C:\Users\Angel\Desktop\hmm\bepin\CustomStreamMaker\AssetExtractor.cs:行号 311
   在 System.Threading.Tasks.Task.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 CustomStreamMaker.AssetLoadWindow.<LoadAssetsToMemory>d__4.MoveNext() 位置 C:\Users\Angel\Desktop\hmm\bepin\CustomStreamMaker\AssetLoadWindow.cs:行号 30
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 CustomStreamMaker.AssetLoadWindow.<StartCachingAssets>d__3.MoveNext() 位置 C:\Users\Angel\Desktop\hmm\bepin\CustomStreamMaker\AssetLoadWindow.cs:行号 23
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 CustomStreamMaker.AssetLoadWindow.<AssetLoadWindow_Shown>d__6.MoveNext() 位置 C:\Users\Angel\Desktop\hmm\bepin\CustomStreamMaker\AssetLoadWindow.cs:行号 60
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)


************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.8.9139.0 built by: NET481REL1LAST_B
    基本代码:file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
CustomStreamMaker
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///D:/downloads/CustomStreamMaker_v1_1_2/CustomStreamMaker/Assemblies/CustomStreamMaker.exe
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.8.9075.0 built by: NET481REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.8.9139.0 built by: NET481REL1LAST_B
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Assembly-CSharp
    程序集版本:0.0.0.0
    Win32 版本:0.0.0.0
    基本代码:file:///D:/downloads/CustomStreamMaker_v1_1_2/CustomStreamMaker/Assemblies/Assembly-CSharp.DLL
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.8.9139.0 built by: NET481REL1LAST_B
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
Accessibility
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
SixLabors.ImageSharp
    程序集版本:2.0.0.0
    Win32 版本:2.1.7.0
    基本代码:file:///D:/downloads/CustomStreamMaker_v1_1_2/CustomStreamMaker/Assemblies/SixLabors.ImageSharp.DLL
----------------------------------------
AssetsTools.NET
    程序集版本:3.0.0.0
    Win32 版本:3.0.0.0
    基本代码:file:///D:/downloads/CustomStreamMaker_v1_1_2/CustomStreamMaker/Assemblies/AssetsTools.NET.DLL
----------------------------------------
AssetsTools.NET.Texture
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///D:/downloads/CustomStreamMaker_v1_1_2/CustomStreamMaker/Assemblies/AssetsTools.NET.Texture.DLL
----------------------------------------
netstandard
    程序集版本:2.1.0.0
    Win32 版本:2.1.0.0
    基本代码:file:///D:/downloads/CustomStreamMaker_v1_1_2/CustomStreamMaker/Assemblies/netstandard.DLL
----------------------------------------


it can give me a windows with the menu and everything but i should first close the loading window and it will give me the editor window with no pics or musics when I have changed them.
![6629eb1b0a84561ef48b5885870e3ee4](https://github.com/amazeedaizee/CustomStreamMaker/assets/131215887/cfd36f9c-f56f-4330-9cee-81f912dcf5ec)

Thank you for your contributions to the open source community of Needy streamer overdose

**Comment by amazeedaizee** [comment] 2024-07-05 05:05
Okay, I think I see what's happening.

For some reason, the program can't find the folder location of the game, where it loads the sprites, music needed, etc, for previews. That's why it's erroring out, and why the program wasn't able to load before (since it does need the Assembly-CSharp.dll to load as well). 

If the game is located somewhere that isn't in the usual Steam location, that can cause problems with the program loading, though I understand other factors can cause this as well.

In the program, if it can't find the game location, the program was supposed to ask the user for a valid location, though it doesn't seem to be working for you right now. Once I get access to my regular PC (which is luckily really soon), I'll try and make some changes as to how the program asks the user for the game location if it can't find the game location itself.

**Comment by AnsonGames** [comment] 2024-07-05 19:04
Thanks for the update! I'll wait for the changes and try again once you've made the adjustments. Appreciate your help with this issue!

**Comment by amazeedaizee** [comment] 2024-07-09 20:36
Hello! Sorry for the wait. I was able to release a new version of the program. Can you test it and see if it works?

**Comment by amazeedaizee** [comment] 2024-08-04 01:53
> Thanks for the update! I'll wait for the changes and try again once you've made the adjustments. Appreciate your help with this issue!

Hi there, it's already been a month since your last reply. Can you test the latest version of the program and see if the problem is resolved?

**Comment by achromatopsic** [comment] 2024-08-05 05:58
Hi, I was also experiencing the issue described with the latest version. What worked for me was putting the .exe in the assemblies folder, and then when it prompted me to choose the install location, I was able to choose it without it infinitely loading and spitting out an error, unlike when the .exe wasn't in the assemblies folder. Thanks. I don't know why it prompts for an installation directory when I have the Steam version of the game installed. Weird. I am also on Windows 11 if that counts.

**Comment by AnsonGames** [comment] 2024-09-14 04:00
sorry for so long not replying. Unluckily my computer was replaced by Chromebook which can't run exe files or sh files or any kind of executable files.😢 I'm really sorry for that.

**Comment by amazeedaizee** [comment] 2024-09-17 21:09
> sorry for so long not replying. Unluckily my computer was replaced by Chromebook which can't run exe files or sh files or any kind of executable files.😢 I'm really sorry for that.

That's ok, was just curious in case the program ended up working for you.

> Hi, I was also experiencing the issue described with the latest version. What worked for me was putting the .exe in the assemblies folder, and then when it prompted me to choose the install location, I was able to choose it without it infinitely loading and spitting out an error, unlike when the .exe wasn't in the assemblies folder. Thanks. I don't know why it prompts for an installation directory when I have the Steam version of the game installed. Weird. I am also on Windows 11 if that counts.

Also sorry for the very late reply, but yeah, I do notice some issues involving searching for the program in Windows 11. As long as the program can still be used despite the directory search failing, via linking to a directory when the program asks, I feel right now resolving why the game directory can't be found automatically in Windows 11 isn't a huge priority right now, though it is something I will be thinking about in the future.

-----

As the program seems to open fine now without closing immediately in the newest version, I'll be closing this issue for now, others who are having still having trouble with opening the application can create a new issue themselves.

**Closed by amazeedaizee** 2024-09-17 21:09 UTC
